# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
tap 'heroku/brew'

# Binaries
brew 'asdf'
# brew 'awscli'
brew 'bash' # Latest Bash version
brew 'bat'
brew 'coreutils' # Those that come with macOS are outdated
brew 'curl-openssl'
brew 'ffmpeg'
brew 'gh'
brew 'git-flow'
brew 'git'
brew 'gnupg2'
brew 'grep'
brew 'imagemagick'
brew 'heroku'
brew 'httpie'
brew 'hub'
brew 'jq'
brew 'jump'
brew 'lsd'
brew 'mackup'
brew 'mysql-client'
# brew 'mas' # Mac App Store manager
brew 'micro'
brew 'orbstack'
brew 'pkg-config' # https://github.com/driesvints/dotfiles/issues/20
brew 'pyenv'
brew 'tor' # Manage the Trash bin
brew 'trash' # Manage the Trash bin
brew 'tree' # List directories in a tree structure
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'libpq'

# Development
# brew 'composer'
# brew 'nginx'
# brew 'redis'
# brew 'yarn'

# Apps
cask 'aerial'
cask 'alfred'
cask 'authy'
cask 'background-music'
# cask 'caffeine'
# cask 'dbngin'
cask 'docker'
cask 'calibre'
cask 'camo-studio'
cask 'dbeaver-community'
# cask 'firefox'
# cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'imageoptim'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'krisp'
cask 'maccy'
cask 'microsoft-teams'
cask 'mysqlworkbench'
cask 'notion'
cask 'orbstack'
cask 'postman'
cask 'pritunl'
# cask 'skype'
cask 'slack'
cask 'spotify'
cask 'sublime-text'
cask 'sublime-merge'
cask 'transmission'
cask 'tunnelbear'
cask 'tor-browser'
cask 'windscribe'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'vlc'
cask 'zed'
cask 'zoom'

# Quicklook
cask 'qlcolorcode'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'
cask 'qlstephen'
